### ISSUE TITLE
feat : search obat

### ISSUE THREAD

**Issue by haniframadhani** [haniframadhani/apotek-rsstt#17]
fitur pencarian obat

---- prerequisite development ----
import database, database sudah ditambahkan `index` agar cepat dalam mencari data

- [ ] fitur search obat berdasarkan `kode obat`, `nama generik`, `nama merek`.
- [ ] hasil pencarian obat ditampilkan di halaman `home/index`.
- [ ] ambil field data yang dibutuhkan saja
- [ ] cegah pencarian jika input field kosong atau tidak ada isinya
- [x] pencarian hanya menggunakan single input field.

---- additional feature ----

- [ ] pencarian tanpa perlu menekan tombol searct / submit

**Comment by mrifainestli7** [comment]
bagaimana user kembali ke halaman index dengan semua data

**Comment by mrifainestli7** [comment]
hyperlink itu ?
